// seeds/02_master_data.ts
import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Clear in reverse FK order
  await knex('master_notice_periods').del();
  await knex('master_currencies').del();
  await knex('master_fields_of_study').del();
  await knex('master_degrees').del();
  await knex('master_languages').del();
  await knex('master_industries').del();
  await knex('master_job_titles').del();
  await knex('master_occupations').del();
  await knex('master_cities').del();
  await knex('master_countries').del();

  // ── 1. COUNTRIES ──────────────────────────────────────────────────────────────
  await knex('master_countries').insert([
    { name: 'Afghanistan',                iso2: 'AF', dial_code: '+93',   flag_emoji: '🇦🇫' },
    { name: 'Albania',                    iso2: 'AL', dial_code: '+355',  flag_emoji: '🇦🇱' },
    { name: 'Algeria',                    iso2: 'DZ', dial_code: '+213',  flag_emoji: '🇩🇿' },
    { name: 'Andorra',                    iso2: 'AD', dial_code: '+376',  flag_emoji: '🇦🇩' },
    { name: 'Angola',                     iso2: 'AO', dial_code: '+244',  flag_emoji: '🇦🇴' },
    { name: 'Argentina',                  iso2: 'AR', dial_code: '+54',   flag_emoji: '🇦🇷' },
    { name: 'Armenia',                    iso2: 'AM', dial_code: '+374',  flag_emoji: '🇦🇲' },
    { name: 'Australia',                  iso2: 'AU', dial_code: '+61',   flag_emoji: '🇦🇺' },
    { name: 'Austria',                    iso2: 'AT', dial_code: '+43',   flag_emoji: '🇦🇹' },
    { name: 'Azerbaijan',                 iso2: 'AZ', dial_code: '+994',  flag_emoji: '🇦🇿' },
    { name: 'Bahrain',                    iso2: 'BH', dial_code: '+973',  flag_emoji: '🇧🇭' },
    { name: 'Bangladesh',                 iso2: 'BD', dial_code: '+880',  flag_emoji: '🇧🇩' },
    { name: 'Belarus',                    iso2: 'BY', dial_code: '+375',  flag_emoji: '🇧🇾' },
    { name: 'Belgium',                    iso2: 'BE', dial_code: '+32',   flag_emoji: '🇧🇪' },
    { name: 'Belize',                     iso2: 'BZ', dial_code: '+501',  flag_emoji: '🇧🇿' },
    { name: 'Benin',                      iso2: 'BJ', dial_code: '+229',  flag_emoji: '🇧🇯' },
    { name: 'Bhutan',                     iso2: 'BT', dial_code: '+975',  flag_emoji: '🇧🇹' },
    { name: 'Bolivia',                    iso2: 'BO', dial_code: '+591',  flag_emoji: '🇧🇴' },
    { name: 'Bosnia and Herzegovina',     iso2: 'BA', dial_code: '+387',  flag_emoji: '🇧🇦' },
    { name: 'Botswana',                   iso2: 'BW', dial_code: '+267',  flag_emoji: '🇧🇼' },
    { name: 'Brazil',                     iso2: 'BR', dial_code: '+55',   flag_emoji: '🇧🇷' },
    { name: 'Brunei',                     iso2: 'BN', dial_code: '+673',  flag_emoji: '🇧🇳' },
    { name: 'Bulgaria',                   iso2: 'BG', dial_code: '+359',  flag_emoji: '🇧🇬' },
    { name: 'Burkina Faso',               iso2: 'BF', dial_code: '+226',  flag_emoji: '🇧🇫' },
    { name: 'Cambodia',                   iso2: 'KH', dial_code: '+855',  flag_emoji: '🇰🇭' },
    { name: 'Cameroon',                   iso2: 'CM', dial_code: '+237',  flag_emoji: '🇨🇲' },
    { name: 'Canada',                     iso2: 'CA', dial_code: '+1',    flag_emoji: '🇨🇦' },
    { name: 'Chile',                      iso2: 'CL', dial_code: '+56',   flag_emoji: '🇨🇱' },
    { name: 'China',                      iso2: 'CN', dial_code: '+86',   flag_emoji: '🇨🇳' },
    { name: 'Colombia',                   iso2: 'CO', dial_code: '+57',   flag_emoji: '🇨🇴' },
    { name: 'Costa Rica',                 iso2: 'CR', dial_code: '+506',  flag_emoji: '🇨🇷' },
    { name: 'Croatia',                    iso2: 'HR', dial_code: '+385',  flag_emoji: '🇭🇷' },
    { name: 'Cuba',                       iso2: 'CU', dial_code: '+53',   flag_emoji: '🇨🇺' },
    { name: 'Cyprus',                     iso2: 'CY', dial_code: '+357',  flag_emoji: '🇨🇾' },
    { name: 'Czech Republic',             iso2: 'CZ', dial_code: '+420',  flag_emoji: '🇨🇿' },
    { name: 'Denmark',                    iso2: 'DK', dial_code: '+45',   flag_emoji: '🇩🇰' },
    { name: 'Dominican Republic',         iso2: 'DO', dial_code: '+1809', flag_emoji: '🇩🇴' },
    { name: 'Ecuador',                    iso2: 'EC', dial_code: '+593',  flag_emoji: '🇪🇨' },
    { name: 'Egypt',                      iso2: 'EG', dial_code: '+20',   flag_emoji: '🇪🇬' },
    { name: 'El Salvador',                iso2: 'SV', dial_code: '+503',  flag_emoji: '🇸🇻' },
    { name: 'Estonia',                    iso2: 'EE', dial_code: '+372',  flag_emoji: '🇪🇪' },
    { name: 'Ethiopia',                   iso2: 'ET', dial_code: '+251',  flag_emoji: '🇪🇹' },
    { name: 'Finland',                    iso2: 'FI', dial_code: '+358',  flag_emoji: '🇫🇮' },
    { name: 'France',                     iso2: 'FR', dial_code: '+33',   flag_emoji: '🇫🇷' },
    { name: 'Georgia',                    iso2: 'GE', dial_code: '+995',  flag_emoji: '🇬🇪' },
    { name: 'Germany',                    iso2: 'DE', dial_code: '+49',   flag_emoji: '🇩🇪' },
    { name: 'Ghana',                      iso2: 'GH', dial_code: '+233',  flag_emoji: '🇬🇭' },
    { name: 'Greece',                     iso2: 'GR', dial_code: '+30',   flag_emoji: '🇬🇷' },
    { name: 'Guatemala',                  iso2: 'GT', dial_code: '+502',  flag_emoji: '🇬🇹' },
    { name: 'Honduras',                   iso2: 'HN', dial_code: '+504',  flag_emoji: '🇭🇳' },
    { name: 'Hungary',                    iso2: 'HU', dial_code: '+36',   flag_emoji: '🇭🇺' },
    { name: 'Iceland',                    iso2: 'IS', dial_code: '+354',  flag_emoji: '🇮🇸' },
    { name: 'India',                      iso2: 'IN', dial_code: '+91',   flag_emoji: '🇮🇳' },
    { name: 'Indonesia',                  iso2: 'ID', dial_code: '+62',   flag_emoji: '🇮🇩' },
    { name: 'Iran',                       iso2: 'IR', dial_code: '+98',   flag_emoji: '🇮🇷' },
    { name: 'Iraq',                       iso2: 'IQ', dial_code: '+964',  flag_emoji: '🇮🇶' },
    { name: 'Ireland',                    iso2: 'IE', dial_code: '+353',  flag_emoji: '🇮🇪' },
    { name: 'Israel',                     iso2: 'IL', dial_code: '+972',  flag_emoji: '🇮🇱' },
    { name: 'Italy',                      iso2: 'IT', dial_code: '+39',   flag_emoji: '🇮🇹' },
    { name: 'Jamaica',                    iso2: 'JM', dial_code: '+1876', flag_emoji: '🇯🇲' },
    { name: 'Japan',                      iso2: 'JP', dial_code: '+81',   flag_emoji: '🇯🇵' },
    { name: 'Jordan',                     iso2: 'JO', dial_code: '+962',  flag_emoji: '🇯🇴' },
    { name: 'Kazakhstan',                 iso2: 'KZ', dial_code: '+7',    flag_emoji: '🇰🇿' },
    { name: 'Kenya',                      iso2: 'KE', dial_code: '+254',  flag_emoji: '🇰🇪' },
    { name: 'Kuwait',                     iso2: 'KW', dial_code: '+965',  flag_emoji: '🇰🇼' },
    { name: 'Kyrgyzstan',                 iso2: 'KG', dial_code: '+996',  flag_emoji: '🇰🇬' },
    { name: 'Laos',                       iso2: 'LA', dial_code: '+856',  flag_emoji: '🇱🇦' },
    { name: 'Latvia',                     iso2: 'LV', dial_code: '+371',  flag_emoji: '🇱🇻' },
    { name: 'Lebanon',                    iso2: 'LB', dial_code: '+961',  flag_emoji: '🇱🇧' },
    { name: 'Libya',                      iso2: 'LY', dial_code: '+218',  flag_emoji: '🇱🇾' },
    { name: 'Lithuania',                  iso2: 'LT', dial_code: '+370',  flag_emoji: '🇱🇹' },
    { name: 'Luxembourg',                 iso2: 'LU', dial_code: '+352',  flag_emoji: '🇱🇺' },
    { name: 'Malaysia',                   iso2: 'MY', dial_code: '+60',   flag_emoji: '🇲🇾' },
    { name: 'Maldives',                   iso2: 'MV', dial_code: '+960',  flag_emoji: '🇲🇻' },
    { name: 'Mali',                       iso2: 'ML', dial_code: '+223',  flag_emoji: '🇲🇱' },
    { name: 'Malta',                      iso2: 'MT', dial_code: '+356',  flag_emoji: '🇲🇹' },
    { name: 'Mexico',                     iso2: 'MX', dial_code: '+52',   flag_emoji: '🇲🇽' },
    { name: 'Moldova',                    iso2: 'MD', dial_code: '+373',  flag_emoji: '🇲🇩' },
    { name: 'Mongolia',                   iso2: 'MN', dial_code: '+976',  flag_emoji: '🇲🇳' },
    { name: 'Morocco',                    iso2: 'MA', dial_code: '+212',  flag_emoji: '🇲🇦' },
    { name: 'Mozambique',                 iso2: 'MZ', dial_code: '+258',  flag_emoji: '🇲🇿' },
    { name: 'Myanmar',                    iso2: 'MM', dial_code: '+95',   flag_emoji: '🇲🇲' },
    { name: 'Nepal',                      iso2: 'NP', dial_code: '+977',  flag_emoji: '🇳🇵' },
    { name: 'Netherlands',                iso2: 'NL', dial_code: '+31',   flag_emoji: '🇳🇱' },
    { name: 'New Zealand',                iso2: 'NZ', dial_code: '+64',   flag_emoji: '🇳🇿' },
    { name: 'Nicaragua',                  iso2: 'NI', dial_code: '+505',  flag_emoji: '🇳🇮' },
    { name: 'Nigeria',                    iso2: 'NG', dial_code: '+234',  flag_emoji: '🇳🇬' },
    { name: 'North Korea',                iso2: 'KP', dial_code: '+850',  flag_emoji: '🇰🇵' },
    { name: 'Norway',                     iso2: 'NO', dial_code: '+47',   flag_emoji: '🇳🇴' },
    { name: 'Oman',                       iso2: 'OM', dial_code: '+968',  flag_emoji: '🇴🇲' },
    { name: 'Pakistan',                   iso2: 'PK', dial_code: '+92',   flag_emoji: '🇵🇰' },
    { name: 'Palestine',                  iso2: 'PS', dial_code: '+970',  flag_emoji: '🇵🇸' },
    { name: 'Panama',                     iso2: 'PA', dial_code: '+507',  flag_emoji: '🇵🇦' },
    { name: 'Paraguay',                   iso2: 'PY', dial_code: '+595',  flag_emoji: '🇵🇾' },
    { name: 'Peru',                       iso2: 'PE', dial_code: '+51',   flag_emoji: '🇵🇪' },
    { name: 'Philippines',                iso2: 'PH', dial_code: '+63',   flag_emoji: '🇵🇭' },
    { name: 'Poland',                     iso2: 'PL', dial_code: '+48',   flag_emoji: '🇵🇱' },
    { name: 'Portugal',                   iso2: 'PT', dial_code: '+351',  flag_emoji: '🇵🇹' },
    { name: 'Qatar',                      iso2: 'QA', dial_code: '+974',  flag_emoji: '🇶🇦' },
    { name: 'Romania',                    iso2: 'RO', dial_code: '+40',   flag_emoji: '🇷🇴' },
    { name: 'Russia',                     iso2: 'RU', dial_code: '+7',    flag_emoji: '🇷🇺' },
    { name: 'Rwanda',                     iso2: 'RW', dial_code: '+250',  flag_emoji: '🇷🇼' },
    { name: 'Saudi Arabia',               iso2: 'SA', dial_code: '+966',  flag_emoji: '🇸🇦' },
    { name: 'Senegal',                    iso2: 'SN', dial_code: '+221',  flag_emoji: '🇸🇳' },
    { name: 'Serbia',                     iso2: 'RS', dial_code: '+381',  flag_emoji: '🇷🇸' },
    { name: 'Sierra Leone',               iso2: 'SL', dial_code: '+232',  flag_emoji: '🇸🇱' },
    { name: 'Singapore',                  iso2: 'SG', dial_code: '+65',   flag_emoji: '🇸🇬' },
    { name: 'Slovakia',                   iso2: 'SK', dial_code: '+421',  flag_emoji: '🇸🇰' },
    { name: 'Slovenia',                   iso2: 'SI', dial_code: '+386',  flag_emoji: '🇸🇮' },
    { name: 'Somalia',                    iso2: 'SO', dial_code: '+252',  flag_emoji: '🇸🇴' },
    { name: 'South Africa',               iso2: 'ZA', dial_code: '+27',   flag_emoji: '🇿🇦' },
    { name: 'South Korea',                iso2: 'KR', dial_code: '+82',   flag_emoji: '🇰🇷' },
    { name: 'Spain',                      iso2: 'ES', dial_code: '+34',   flag_emoji: '🇪🇸' },
    { name: 'Sri Lanka',                  iso2: 'LK', dial_code: '+94',   flag_emoji: '🇱🇰' },
    { name: 'Sudan',                      iso2: 'SD', dial_code: '+249',  flag_emoji: '🇸🇩' },
    { name: 'Sweden',                     iso2: 'SE', dial_code: '+46',   flag_emoji: '🇸🇪' },
    { name: 'Switzerland',                iso2: 'CH', dial_code: '+41',   flag_emoji: '🇨🇭' },
    { name: 'Syria',                      iso2: 'SY', dial_code: '+963',  flag_emoji: '🇸🇾' },
    { name: 'Taiwan',                     iso2: 'TW', dial_code: '+886',  flag_emoji: '🇹🇼' },
    { name: 'Tajikistan',                 iso2: 'TJ', dial_code: '+992',  flag_emoji: '🇹🇯' },
    { name: 'Tanzania',                   iso2: 'TZ', dial_code: '+255',  flag_emoji: '🇹🇿' },
    { name: 'Thailand',                   iso2: 'TH', dial_code: '+66',   flag_emoji: '🇹🇭' },
    { name: 'Tunisia',                    iso2: 'TN', dial_code: '+216',  flag_emoji: '🇹🇳' },
    { name: 'Turkey',                     iso2: 'TR', dial_code: '+90',   flag_emoji: '🇹🇷' },
    { name: 'Turkmenistan',               iso2: 'TM', dial_code: '+993',  flag_emoji: '🇹🇲' },
    { name: 'Uganda',                     iso2: 'UG', dial_code: '+256',  flag_emoji: '🇺🇬' },
    { name: 'Ukraine',                    iso2: 'UA', dial_code: '+380',  flag_emoji: '🇺🇦' },
    { name: 'United Arab Emirates',       iso2: 'AE', dial_code: '+971',  flag_emoji: '🇦🇪' },
    { name: 'United Kingdom',             iso2: 'GB', dial_code: '+44',   flag_emoji: '🇬🇧' },
    { name: 'United States',              iso2: 'US', dial_code: '+1',    flag_emoji: '🇺🇸' },
    { name: 'Uruguay',                    iso2: 'UY', dial_code: '+598',  flag_emoji: '🇺🇾' },
    { name: 'Uzbekistan',                 iso2: 'UZ', dial_code: '+998',  flag_emoji: '🇺🇿' },
    { name: 'Venezuela',                  iso2: 'VE', dial_code: '+58',   flag_emoji: '🇻🇪' },
    { name: 'Vietnam',                    iso2: 'VN', dial_code: '+84',   flag_emoji: '🇻🇳' },
    { name: 'Yemen',                      iso2: 'YE', dial_code: '+967',  flag_emoji: '🇾🇪' },
    { name: 'Zambia',                     iso2: 'ZM', dial_code: '+260',  flag_emoji: '🇿🇲' },
    { name: 'Zimbabwe',                   iso2: 'ZW', dial_code: '+263',  flag_emoji: '🇿🇼' },
  ]);

  // ── 2. CITIES (major cities per country, keyed by iso2) ──────────────────────
  const countryIds = await knex('master_countries').select('id', 'iso2');
  const cid = (iso2: string) => countryIds.find((c) => c.iso2 === iso2)?.id;

  const cityRows: { country_id: number; name: string }[] = [
    // Australia
    ...['Sydney','Melbourne','Brisbane','Perth','Adelaide','Canberra','Hobart','Darwin','Gold Coast','Newcastle'].map(n=>({country_id:cid('AU'),name:n})),
    // Austria
    ...['Vienna','Graz','Linz','Salzburg','Innsbruck'].map(n=>({country_id:cid('AT'),name:n})),
    // Bangladesh
    ...['Dhaka','Chittagong','Sylhet','Rajshahi','Khulna'].map(n=>({country_id:cid('BD'),name:n})),
    // Belgium
    ...['Brussels','Antwerp','Ghent','Bruges','Liège'].map(n=>({country_id:cid('BE'),name:n})),
    // Brazil
    ...['São Paulo','Rio de Janeiro','Brasília','Salvador','Fortaleza','Belo Horizonte','Manaus','Curitiba','Recife','Porto Alegre'].map(n=>({country_id:cid('BR'),name:n})),
    // Canada
    ...['Toronto','Montreal','Vancouver','Calgary','Edmonton','Ottawa','Winnipeg','Quebec City','Hamilton','Kitchener'].map(n=>({country_id:cid('CA'),name:n})),
    // Chile
    ...['Santiago','Valparaíso','Concepción','Antofagasta','Viña del Mar'].map(n=>({country_id:cid('CL'),name:n})),
    // China
    ...['Beijing','Shanghai','Guangzhou','Shenzhen','Chengdu','Hangzhou','Wuhan','Xi\'an','Nanjing','Tianjin','Chongqing','Suzhou'].map(n=>({country_id:cid('CN'),name:n})),
    // Colombia
    ...['Bogotá','Medellín','Cali','Barranquilla','Cartagena'].map(n=>({country_id:cid('CO'),name:n})),
    // Czech Republic
    ...['Prague','Brno','Ostrava','Pilsen','Liberec'].map(n=>({country_id:cid('CZ'),name:n})),
    // Denmark
    ...['Copenhagen','Aarhus','Odense','Aalborg','Esbjerg'].map(n=>({country_id:cid('DK'),name:n})),
    // Egypt
    ...['Cairo','Alexandria','Giza','Luxor','Aswan','Port Said'].map(n=>({country_id:cid('EG'),name:n})),
    // Finland
    ...['Helsinki','Espoo','Tampere','Turku','Oulu'].map(n=>({country_id:cid('FI'),name:n})),
    // France
    ...['Paris','Lyon','Marseille','Toulouse','Nice','Nantes','Bordeaux','Strasbourg','Montpellier','Lille'].map(n=>({country_id:cid('FR'),name:n})),
    // Germany
    ...['Berlin','Hamburg','Munich','Cologne','Frankfurt','Stuttgart','Düsseldorf','Dortmund','Leipzig','Dresden'].map(n=>({country_id:cid('DE'),name:n})),
    // Ghana
    ...['Accra','Kumasi','Tamale','Sekondi-Takoradi'].map(n=>({country_id:cid('GH'),name:n})),
    // Greece
    ...['Athens','Thessaloniki','Patras','Heraklion','Larissa'].map(n=>({country_id:cid('GR'),name:n})),
    // Hungary
    ...['Budapest','Debrecen','Miskolc','Szeged','Pécs'].map(n=>({country_id:cid('HU'),name:n})),
    // India
    ...['Mumbai','Delhi','Bangalore','Hyderabad','Chennai','Kolkata','Ahmedabad','Pune','Surat','Jaipur','Lucknow','Kanpur','Nagpur','Indore','Thane','Bhopal','Visakhapatnam','Pimpri-Chinchwad','Patna','Vadodara','Chandigarh','Kochi','Coimbatore','Mysore','Noida','Gurgaon'].map(n=>({country_id:cid('IN'),name:n})),
    // Indonesia
    ...['Jakarta','Surabaya','Bandung','Medan','Semarang','Makassar','Palembang','Yogyakarta'].map(n=>({country_id:cid('ID'),name:n})),
    // Ireland
    ...['Dublin','Cork','Limerick','Galway','Waterford'].map(n=>({country_id:cid('IE'),name:n})),
    // Israel
    ...['Tel Aviv','Jerusalem','Haifa','Beersheba','Netanya'].map(n=>({country_id:cid('IL'),name:n})),
    // Italy
    ...['Rome','Milan','Naples','Turin','Palermo','Genoa','Bologna','Florence','Venice','Catania'].map(n=>({country_id:cid('IT'),name:n})),
    // Japan
    ...['Tokyo','Yokohama','Osaka','Nagoya','Sapporo','Fukuoka','Kobe','Kyoto','Hiroshima','Sendai'].map(n=>({country_id:cid('JP'),name:n})),
    // Jordan
    ...['Amman','Zarqa','Irbid','Aqaba'].map(n=>({country_id:cid('JO'),name:n})),
    // Kenya
    ...['Nairobi','Mombasa','Kisumu','Nakuru','Eldoret'].map(n=>({country_id:cid('KE'),name:n})),
    // Kuwait
    ...['Kuwait City','Hawalli','Salmiya','Farwaniya'].map(n=>({country_id:cid('KW'),name:n})),
    // Malaysia
    ...['Kuala Lumpur','George Town','Ipoh','Johor Bahru','Petaling Jaya','Shah Alam','Subang Jaya','Kota Kinabalu'].map(n=>({country_id:cid('MY'),name:n})),
    // Mexico
    ...['Mexico City','Guadalajara','Monterrey','Puebla','Tijuana','León','Juárez','Mérida','Querétaro'].map(n=>({country_id:cid('MX'),name:n})),
    // Morocco
    ...['Casablanca','Rabat','Marrakech','Fes','Tangier','Agadir'].map(n=>({country_id:cid('MA'),name:n})),
    // Nepal
    ...['Kathmandu','Pokhara','Lalitpur','Bharatpur','Biratnagar'].map(n=>({country_id:cid('NP'),name:n})),
    // Netherlands
    ...['Amsterdam','Rotterdam','The Hague','Utrecht','Eindhoven','Tilburg','Groningen'].map(n=>({country_id:cid('NL'),name:n})),
    // New Zealand
    ...['Auckland','Wellington','Christchurch','Hamilton','Tauranga','Dunedin'].map(n=>({country_id:cid('NZ'),name:n})),
    // Nigeria
    ...['Lagos','Abuja','Kano','Ibadan','Port Harcourt','Benin City','Kaduna','Enugu'].map(n=>({country_id:cid('NG'),name:n})),
    // Norway
    ...['Oslo','Bergen','Trondheim','Stavanger','Tromsø'].map(n=>({country_id:cid('NO'),name:n})),
    // Oman
    ...['Muscat','Salalah','Sohar','Nizwa'].map(n=>({country_id:cid('OM'),name:n})),
    // Pakistan
    ...['Karachi','Lahore','Islamabad','Rawalpindi','Faisalabad','Multan','Peshawar','Quetta','Sialkot'].map(n=>({country_id:cid('PK'),name:n})),
    // Philippines
    ...['Manila','Quezon City','Davao','Caloocan','Zamboanga','Cebu City','Pasig'].map(n=>({country_id:cid('PH'),name:n})),
    // Poland
    ...['Warsaw','Kraków','Łódź','Wrocław','Poznań','Gdańsk','Szczecin'].map(n=>({country_id:cid('PL'),name:n})),
    // Portugal
    ...['Lisbon','Porto','Braga','Amadora','Setúbal'].map(n=>({country_id:cid('PT'),name:n})),
    // Qatar
    ...['Doha','Al Wakrah','Al Khor','Lusail'].map(n=>({country_id:cid('QA'),name:n})),
    // Romania
    ...['Bucharest','Cluj-Napoca','Timișoara','Iași','Constanța'].map(n=>({country_id:cid('RO'),name:n})),
    // Russia
    ...['Moscow','Saint Petersburg','Novosibirsk','Yekaterinburg','Kazan','Nizhny Novgorod','Chelyabinsk','Samara','Omsk','Rostov-on-Don'].map(n=>({country_id:cid('RU'),name:n})),
    // Saudi Arabia
    ...['Riyadh','Jeddah','Mecca','Medina','Dammam','Khobar','Tabuk','Abha','Taif'].map(n=>({country_id:cid('SA'),name:n})),
    // Singapore
    ...['Singapore'].map(n=>({country_id:cid('SG'),name:n})),
    // South Africa
    ...['Johannesburg','Cape Town','Durban','Pretoria','Port Elizabeth','Bloemfontein'].map(n=>({country_id:cid('ZA'),name:n})),
    // South Korea
    ...['Seoul','Busan','Incheon','Daegu','Daejeon','Gwangju','Suwon'].map(n=>({country_id:cid('KR'),name:n})),
    // Spain
    ...['Madrid','Barcelona','Valencia','Seville','Zaragoza','Málaga','Murcia','Palma','Bilbao'].map(n=>({country_id:cid('ES'),name:n})),
    // Sri Lanka
    ...['Colombo','Kandy','Galle','Negombo','Jaffna'].map(n=>({country_id:cid('LK'),name:n})),
    // Sweden
    ...['Stockholm','Gothenburg','Malmö','Uppsala','Linköping'].map(n=>({country_id:cid('SE'),name:n})),
    // Switzerland
    ...['Zurich','Geneva','Basel','Bern','Lausanne'].map(n=>({country_id:cid('CH'),name:n})),
    // Taiwan
    ...['Taipei','New Taipei','Kaohsiung','Taichung','Tainan'].map(n=>({country_id:cid('TW'),name:n})),
    // Thailand
    ...['Bangkok','Chiang Mai','Phuket','Pattaya','Nonthaburi','Hat Yai'].map(n=>({country_id:cid('TH'),name:n})),
    // Turkey
    ...['Istanbul','Ankara','Izmir','Bursa','Antalya','Adana','Konya'].map(n=>({country_id:cid('TR'),name:n})),
    // Ukraine
    ...['Kyiv','Kharkiv','Odessa','Dnipro','Lviv','Zaporizhzhia'].map(n=>({country_id:cid('UA'),name:n})),
    // United Arab Emirates
    ...['Dubai','Abu Dhabi','Sharjah','Ajman','Ras Al Khaimah','Fujairah','Al Ain'].map(n=>({country_id:cid('AE'),name:n})),
    // United Kingdom
    ...['London','Birmingham','Leeds','Glasgow','Sheffield','Bradford','Edinburgh','Liverpool','Manchester','Bristol','Leicester','Cardiff','Newcastle','Nottingham'].map(n=>({country_id:cid('GB'),name:n})),
    // United States
    ...['New York','Los Angeles','Chicago','Houston','Phoenix','Philadelphia','San Antonio','San Diego','Dallas','San Jose','Austin','Jacksonville','Fort Worth','Columbus','Charlotte','Indianapolis','San Francisco','Seattle','Denver','Washington DC','Nashville','Oklahoma City','El Paso','Boston','Portland','Las Vegas','Memphis','Louisville','Baltimore','Milwaukee','Albuquerque','Tucson','Fresno','Sacramento','Atlanta','Kansas City','Omaha','Miami','Minneapolis'].map(n=>({country_id:cid('US'),name:n})),
    // Vietnam
    ...['Ho Chi Minh City','Hanoi','Da Nang','Haiphong','Can Tho'].map(n=>({country_id:cid('VN'),name:n})),
  ];

  // batch insert cities (filter out any undefined country_ids)
  const validCities = cityRows.filter((r) => r.country_id !== undefined);
  for (let i = 0; i < validCities.length; i += 500) {
    await knex('master_cities').insert(validCities.slice(i, i + 500));
  }

  // ── 3. OCCUPATIONS ────────────────────────────────────────────────────────────
  await knex('master_occupations').insert([
    { name: 'Software Engineering' },
    { name: 'Data & Analytics' },
    { name: 'DevOps & Cloud' },
    { name: 'Cybersecurity' },
    { name: 'IT & Systems' },
    { name: 'Product Management' },
    { name: 'UX / UI Design' },
    { name: 'Graphic & Visual Design' },
    { name: 'Marketing' },
    { name: 'Sales & Business Development' },
    { name: 'Customer Success & Support' },
    { name: 'Finance & Accounting' },
    { name: 'Human Resources' },
    { name: 'Operations & Logistics' },
    { name: 'Legal & Compliance' },
    { name: 'Healthcare & Medicine' },
    { name: 'Nursing & Allied Health' },
    { name: 'Education & Training' },
    { name: 'Research & Science' },
    { name: 'Engineering (Non-IT)' },
    { name: 'Architecture & Construction' },
    { name: 'Supply Chain & Procurement' },
    { name: 'Media & Communications' },
    { name: 'Writing & Content' },
    { name: 'Project Management' },
    { name: 'Consulting' },
    { name: 'Entrepreneurship' },
    { name: 'Administrative & Executive Support' },
    { name: 'Hospitality & Tourism' },
    { name: 'Retail & E-commerce' },
    { name: 'Real Estate' },
    { name: 'Agriculture & Environment' },
    { name: 'Transportation & Automotive' },
    { name: 'Manufacturing & Quality' },
    { name: 'Non-profit & Social Work' },
  ]);

  // ── 4. JOB TITLES (linked to occupations) ────────────────────────────────────
  const occRows = await knex('master_occupations').select('id', 'name');
  const oid = (name: string) => occRows.find((o) => o.name === name)?.id;

  await knex('master_job_titles').insert([
    // Software Engineering
    { occupation_id: oid('Software Engineering'), title: 'Software Engineer' },
    { occupation_id: oid('Software Engineering'), title: 'Frontend Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Backend Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Full Stack Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Mobile Developer (iOS)' },
    { occupation_id: oid('Software Engineering'), title: 'Mobile Developer (Android)' },
    { occupation_id: oid('Software Engineering'), title: 'React Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Angular Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Node.js Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Python Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Java Developer' },
    { occupation_id: oid('Software Engineering'), title: '.NET Developer' },
    { occupation_id: oid('Software Engineering'), title: 'Embedded Systems Engineer' },
    { occupation_id: oid('Software Engineering'), title: 'QA Engineer' },
    { occupation_id: oid('Software Engineering'), title: 'Automation Test Engineer' },
    { occupation_id: oid('Software Engineering'), title: 'Site Reliability Engineer' },
    { occupation_id: oid('Software Engineering'), title: 'Software Architect' },
    { occupation_id: oid('Software Engineering'), title: 'Engineering Manager' },
    // Data & Analytics
    { occupation_id: oid('Data & Analytics'), title: 'Data Analyst' },
    { occupation_id: oid('Data & Analytics'), title: 'Data Scientist' },
    { occupation_id: oid('Data & Analytics'), title: 'Machine Learning Engineer' },
    { occupation_id: oid('Data & Analytics'), title: 'AI Engineer' },
    { occupation_id: oid('Data & Analytics'), title: 'Data Engineer' },
    { occupation_id: oid('Data & Analytics'), title: 'Business Intelligence Analyst' },
    { occupation_id: oid('Data & Analytics'), title: 'Analytics Engineer' },
    { occupation_id: oid('Data & Analytics'), title: 'Data Architect' },
    { occupation_id: oid('Data & Analytics'), title: 'NLP Engineer' },
    // DevOps & Cloud
    { occupation_id: oid('DevOps & Cloud'), title: 'DevOps Engineer' },
    { occupation_id: oid('DevOps & Cloud'), title: 'Cloud Engineer' },
    { occupation_id: oid('DevOps & Cloud'), title: 'Cloud Architect' },
    { occupation_id: oid('DevOps & Cloud'), title: 'Platform Engineer' },
    { occupation_id: oid('DevOps & Cloud'), title: 'Infrastructure Engineer' },
    { occupation_id: oid('DevOps & Cloud'), title: 'Kubernetes Engineer' },
    { occupation_id: oid('DevOps & Cloud'), title: 'AWS Solutions Architect' },
    { occupation_id: oid('DevOps & Cloud'), title: 'Azure Engineer' },
    // Cybersecurity
    { occupation_id: oid('Cybersecurity'), title: 'Cybersecurity Analyst' },
    { occupation_id: oid('Cybersecurity'), title: 'Security Engineer' },
    { occupation_id: oid('Cybersecurity'), title: 'Penetration Tester' },
    { occupation_id: oid('Cybersecurity'), title: 'Information Security Manager' },
    { occupation_id: oid('Cybersecurity'), title: 'SOC Analyst' },
    { occupation_id: oid('Cybersecurity'), title: 'GRC Analyst' },
    // IT & Systems
    { occupation_id: oid('IT & Systems'), title: 'IT Support Specialist' },
    { occupation_id: oid('IT & Systems'), title: 'Systems Administrator' },
    { occupation_id: oid('IT & Systems'), title: 'Network Engineer' },
    { occupation_id: oid('IT & Systems'), title: 'IT Manager' },
    { occupation_id: oid('IT & Systems'), title: 'Database Administrator' },
    { occupation_id: oid('IT & Systems'), title: 'IT Project Manager' },
    { occupation_id: oid('IT & Systems'), title: 'ERP Consultant' },
    // Product Management
    { occupation_id: oid('Product Management'), title: 'Product Manager' },
    { occupation_id: oid('Product Management'), title: 'Senior Product Manager' },
    { occupation_id: oid('Product Management'), title: 'Product Owner' },
    { occupation_id: oid('Product Management'), title: 'Technical Product Manager' },
    { occupation_id: oid('Product Management'), title: 'Director of Product' },
    { occupation_id: oid('Product Management'), title: 'Chief Product Officer' },
    // UX / UI Design
    { occupation_id: oid('UX / UI Design'), title: 'UX Designer' },
    { occupation_id: oid('UX / UI Design'), title: 'UI Designer' },
    { occupation_id: oid('UX / UI Design'), title: 'Product Designer' },
    { occupation_id: oid('UX / UI Design'), title: 'UX Researcher' },
    { occupation_id: oid('UX / UI Design'), title: 'Interaction Designer' },
    { occupation_id: oid('UX / UI Design'), title: 'Design Lead' },
    // Graphic & Visual Design
    { occupation_id: oid('Graphic & Visual Design'), title: 'Graphic Designer' },
    { occupation_id: oid('Graphic & Visual Design'), title: 'Motion Designer' },
    { occupation_id: oid('Graphic & Visual Design'), title: 'Brand Designer' },
    { occupation_id: oid('Graphic & Visual Design'), title: 'Creative Director' },
    { occupation_id: oid('Graphic & Visual Design'), title: 'Visual Designer' },
    // Marketing
    { occupation_id: oid('Marketing'), title: 'Marketing Manager' },
    { occupation_id: oid('Marketing'), title: 'Digital Marketing Specialist' },
    { occupation_id: oid('Marketing'), title: 'SEO Specialist' },
    { occupation_id: oid('Marketing'), title: 'Growth Hacker' },
    { occupation_id: oid('Marketing'), title: 'Social Media Manager' },
    { occupation_id: oid('Marketing'), title: 'Email Marketing Specialist' },
    { occupation_id: oid('Marketing'), title: 'Marketing Analyst' },
    { occupation_id: oid('Marketing'), title: 'Brand Manager' },
    { occupation_id: oid('Marketing'), title: 'CMO' },
    // Sales & Business Development
    { occupation_id: oid('Sales & Business Development'), title: 'Sales Representative' },
    { occupation_id: oid('Sales & Business Development'), title: 'Account Executive' },
    { occupation_id: oid('Sales & Business Development'), title: 'Business Development Manager' },
    { occupation_id: oid('Sales & Business Development'), title: 'Sales Manager' },
    { occupation_id: oid('Sales & Business Development'), title: 'VP of Sales' },
    { occupation_id: oid('Sales & Business Development'), title: 'Inside Sales Representative' },
    { occupation_id: oid('Sales & Business Development'), title: 'Pre-Sales Consultant' },
    // Customer Success & Support
    { occupation_id: oid('Customer Success & Support'), title: 'Customer Success Manager' },
    { occupation_id: oid('Customer Success & Support'), title: 'Customer Support Specialist' },
    { occupation_id: oid('Customer Success & Support'), title: 'Technical Support Engineer' },
    { occupation_id: oid('Customer Success & Support'), title: 'Customer Experience Manager' },
    // Finance & Accounting
    { occupation_id: oid('Finance & Accounting'), title: 'Accountant' },
    { occupation_id: oid('Finance & Accounting'), title: 'Financial Analyst' },
    { occupation_id: oid('Finance & Accounting'), title: 'Finance Manager' },
    { occupation_id: oid('Finance & Accounting'), title: 'CFO' },
    { occupation_id: oid('Finance & Accounting'), title: 'Auditor' },
    { occupation_id: oid('Finance & Accounting'), title: 'Tax Specialist' },
    { occupation_id: oid('Finance & Accounting'), title: 'Treasury Analyst' },
    { occupation_id: oid('Finance & Accounting'), title: 'Payroll Specialist' },
    // Human Resources
    { occupation_id: oid('Human Resources'), title: 'HR Manager' },
    { occupation_id: oid('Human Resources'), title: 'HR Business Partner' },
    { occupation_id: oid('Human Resources'), title: 'Talent Acquisition Specialist' },
    { occupation_id: oid('Human Resources'), title: 'Recruiter' },
    { occupation_id: oid('Human Resources'), title: 'Compensation & Benefits Analyst' },
    { occupation_id: oid('Human Resources'), title: 'CHRO' },
    { occupation_id: oid('Human Resources'), title: 'HR Coordinator' },
    { occupation_id: oid('Human Resources'), title: 'Learning & Development Specialist' },
    // Operations & Logistics
    { occupation_id: oid('Operations & Logistics'), title: 'Operations Manager' },
    { occupation_id: oid('Operations & Logistics'), title: 'Logistics Coordinator' },
    { occupation_id: oid('Operations & Logistics'), title: 'Supply Chain Manager' },
    { occupation_id: oid('Operations & Logistics'), title: 'Warehouse Manager' },
    { occupation_id: oid('Operations & Logistics'), title: 'COO' },
    // Legal & Compliance
    { occupation_id: oid('Legal & Compliance'), title: 'Legal Counsel' },
    { occupation_id: oid('Legal & Compliance'), title: 'Compliance Officer' },
    { occupation_id: oid('Legal & Compliance'), title: 'Contract Specialist' },
    { occupation_id: oid('Legal & Compliance'), title: 'Paralegal' },
    { occupation_id: oid('Legal & Compliance'), title: 'General Counsel' },
    // Healthcare & Medicine
    { occupation_id: oid('Healthcare & Medicine'), title: 'General Practitioner' },
    { occupation_id: oid('Healthcare & Medicine'), title: 'Surgeon' },
    { occupation_id: oid('Healthcare & Medicine'), title: 'Specialist Physician' },
    { occupation_id: oid('Healthcare & Medicine'), title: 'Dentist' },
    { occupation_id: oid('Healthcare & Medicine'), title: 'Pharmacist' },
    { occupation_id: oid('Healthcare & Medicine'), title: 'Medical Director' },
    // Nursing & Allied Health
    { occupation_id: oid('Nursing & Allied Health'), title: 'Registered Nurse' },
    { occupation_id: oid('Nursing & Allied Health'), title: 'Nurse Practitioner' },
    { occupation_id: oid('Nursing & Allied Health'), title: 'Physiotherapist' },
    { occupation_id: oid('Nursing & Allied Health'), title: 'Occupational Therapist' },
    { occupation_id: oid('Nursing & Allied Health'), title: 'Radiographer' },
    { occupation_id: oid('Nursing & Allied Health'), title: 'Medical Lab Technologist' },
    // Education & Training
    { occupation_id: oid('Education & Training'), title: 'Teacher' },
    { occupation_id: oid('Education & Training'), title: 'University Lecturer' },
    { occupation_id: oid('Education & Training'), title: 'Instructional Designer' },
    { occupation_id: oid('Education & Training'), title: 'Corporate Trainer' },
    { occupation_id: oid('Education & Training'), title: 'School Principal' },
    // Research & Science
    { occupation_id: oid('Research & Science'), title: 'Research Scientist' },
    { occupation_id: oid('Research & Science'), title: 'Research Analyst' },
    { occupation_id: oid('Research & Science'), title: 'Biomedical Researcher' },
    { occupation_id: oid('Research & Science'), title: 'Chemist' },
    { occupation_id: oid('Research & Science'), title: 'Biologist' },
    // Engineering (Non-IT)
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Mechanical Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Electrical Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Civil Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Chemical Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Aerospace Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Industrial Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Structural Engineer' },
    { occupation_id: oid('Engineering (Non-IT)'), title: 'Petroleum Engineer' },
    // Architecture & Construction
    { occupation_id: oid('Architecture & Construction'), title: 'Architect' },
    { occupation_id: oid('Architecture & Construction'), title: 'Interior Designer' },
    { occupation_id: oid('Architecture & Construction'), title: 'Construction Manager' },
    { occupation_id: oid('Architecture & Construction'), title: 'Urban Planner' },
    { occupation_id: oid('Architecture & Construction'), title: 'Site Engineer' },
    // Project Management
    { occupation_id: oid('Project Management'), title: 'Project Manager' },
    { occupation_id: oid('Project Management'), title: 'Senior Project Manager' },
    { occupation_id: oid('Project Management'), title: 'Program Manager' },
    { occupation_id: oid('Project Management'), title: 'Scrum Master' },
    { occupation_id: oid('Project Management'), title: 'Agile Coach' },
    { occupation_id: oid('Project Management'), title: 'PMO Analyst' },
    // Consulting
    { occupation_id: oid('Consulting'), title: 'Management Consultant' },
    { occupation_id: oid('Consulting'), title: 'Strategy Consultant' },
    { occupation_id: oid('Consulting'), title: 'IT Consultant' },
    { occupation_id: oid('Consulting'), title: 'Financial Consultant' },
    // Writing & Content
    { occupation_id: oid('Writing & Content'), title: 'Content Writer' },
    { occupation_id: oid('Writing & Content'), title: 'Copywriter' },
    { occupation_id: oid('Writing & Content'), title: 'Technical Writer' },
    { occupation_id: oid('Writing & Content'), title: 'Content Strategist' },
    { occupation_id: oid('Writing & Content'), title: 'Journalist' },
    { occupation_id: oid('Writing & Content'), title: 'Editor' },
    // Media & Communications
    { occupation_id: oid('Media & Communications'), title: 'Public Relations Manager' },
    { occupation_id: oid('Media & Communications'), title: 'Communications Specialist' },
    { occupation_id: oid('Media & Communications'), title: 'Video Producer' },
    { occupation_id: oid('Media & Communications'), title: 'Photographer' },
    { occupation_id: oid('Media & Communications'), title: 'Podcast Producer' },
    // Administrative
    { occupation_id: oid('Administrative & Executive Support'), title: 'Executive Assistant' },
    { occupation_id: oid('Administrative & Executive Support'), title: 'Office Manager' },
    { occupation_id: oid('Administrative & Executive Support'), title: 'Administrative Coordinator' },
    { occupation_id: oid('Administrative & Executive Support'), title: 'Receptionist' },
    // Hospitality & Tourism
    { occupation_id: oid('Hospitality & Tourism'), title: 'Hotel Manager' },
    { occupation_id: oid('Hospitality & Tourism'), title: 'Chef' },
    { occupation_id: oid('Hospitality & Tourism'), title: 'Tourism Coordinator' },
    { occupation_id: oid('Hospitality & Tourism'), title: 'Event Manager' },
    { occupation_id: oid('Hospitality & Tourism'), title: 'Restaurant Manager' },
    // Retail & E-commerce
    { occupation_id: oid('Retail & E-commerce'), title: 'Retail Manager' },
    { occupation_id: oid('Retail & E-commerce'), title: 'E-commerce Manager' },
    { occupation_id: oid('Retail & E-commerce'), title: 'Merchandiser' },
    { occupation_id: oid('Retail & E-commerce'), title: 'Category Manager' },
    // Real Estate
    { occupation_id: oid('Real Estate'), title: 'Real Estate Agent' },
    { occupation_id: oid('Real Estate'), title: 'Property Manager' },
    { occupation_id: oid('Real Estate'), title: 'Real Estate Analyst' },
    // Supply Chain & Procurement
    { occupation_id: oid('Supply Chain & Procurement'), title: 'Procurement Manager' },
    { occupation_id: oid('Supply Chain & Procurement'), title: 'Sourcing Specialist' },
    { occupation_id: oid('Supply Chain & Procurement'), title: 'Inventory Analyst' },
    // Manufacturing & Quality
    { occupation_id: oid('Manufacturing & Quality'), title: 'Quality Engineer' },
    { occupation_id: oid('Manufacturing & Quality'), title: 'Production Manager' },
    { occupation_id: oid('Manufacturing & Quality'), title: 'Process Engineer' },
    { occupation_id: oid('Manufacturing & Quality'), title: 'Maintenance Technician' },
    // Non-profit
    { occupation_id: oid('Non-profit & Social Work'), title: 'Program Coordinator' },
    { occupation_id: oid('Non-profit & Social Work'), title: 'Social Worker' },
    { occupation_id: oid('Non-profit & Social Work'), title: 'Community Manager' },
    { occupation_id: oid('Non-profit & Social Work'), title: 'Fundraising Manager' },
    // Entrepreneurship
    { occupation_id: oid('Entrepreneurship'), title: 'Founder / CEO' },
    { occupation_id: oid('Entrepreneurship'), title: 'Co-Founder' },
    { occupation_id: oid('Entrepreneurship'), title: 'Startup Advisor' },
    // Agriculture
    { occupation_id: oid('Agriculture & Environment'), title: 'Agronomist' },
    { occupation_id: oid('Agriculture & Environment'), title: 'Environmental Consultant' },
    { occupation_id: oid('Agriculture & Environment'), title: 'Farm Manager' },
    // Transportation
    { occupation_id: oid('Transportation & Automotive'), title: 'Fleet Manager' },
    { occupation_id: oid('Transportation & Automotive'), title: 'Automotive Engineer' },
    { occupation_id: oid('Transportation & Automotive'), title: 'Logistics Driver' },
  ]);

  // ── 5. INDUSTRIES ─────────────────────────────────────────────────────────────
  await knex('master_industries').insert([
    { name: 'Technology & Software' },
    { name: 'Financial Services & Banking' },
    { name: 'Healthcare & Pharmaceuticals' },
    { name: 'Education & E-learning' },
    { name: 'Retail & E-commerce' },
    { name: 'Manufacturing' },
    { name: 'Oil, Gas & Energy' },
    { name: 'Construction & Real Estate' },
    { name: 'Telecommunications' },
    { name: 'Media & Entertainment' },
    { name: 'Transportation & Logistics' },
    { name: 'Hospitality & Tourism' },
    { name: 'Government & Public Sector' },
    { name: 'Non-profit & NGO' },
    { name: 'Agriculture & Food' },
    { name: 'Automotive' },
    { name: 'Aerospace & Defence' },
    { name: 'Legal & Professional Services' },
    { name: 'Consulting & Advisory' },
    { name: 'Insurance' },
    { name: 'Human Resources & Staffing' },
    { name: 'Marketing & Advertising' },
    { name: 'Sports & Fitness' },
    { name: 'Fashion & Apparel' },
    { name: 'Chemicals & Materials' },
    { name: 'Mining & Natural Resources' },
    { name: 'Research & Development' },
    { name: 'Architecture & Engineering' },
    { name: 'Environmental Services' },
    { name: 'Social Services' },
    { name: 'Arts & Design' },
    { name: 'Publishing & Journalism' },
    { name: 'Biotechnology' },
    { name: 'Semiconductor & Electronics' },
    { name: 'Supply Chain & Procurement' },
  ]);

  // ── 6. LANGUAGES ─────────────────────────────────────────────────────────────
  await knex('master_languages').insert([
    { name: 'Afrikaans' }, { name: 'Albanian' }, { name: 'Amharic' },
    { name: 'Arabic' }, { name: 'Armenian' }, { name: 'Azerbaijani' },
    { name: 'Basque' }, { name: 'Belarusian' }, { name: 'Bengali' },
    { name: 'Bosnian' }, { name: 'Bulgarian' }, { name: 'Burmese' },
    { name: 'Catalan' }, { name: 'Chinese (Cantonese)' }, { name: 'Chinese (Mandarin)' },
    { name: 'Croatian' }, { name: 'Czech' }, { name: 'Danish' },
    { name: 'Dari' }, { name: 'Dutch' }, { name: 'English' },
    { name: 'Estonian' }, { name: 'Farsi' }, { name: 'Filipino' },
    { name: 'Finnish' }, { name: 'French' }, { name: 'Georgian' },
    { name: 'German' }, { name: 'Greek' }, { name: 'Gujarati' },
    { name: 'Hausa' }, { name: 'Hebrew' }, { name: 'Hindi' },
    { name: 'Hungarian' }, { name: 'Icelandic' }, { name: 'Igbo' },
    { name: 'Indonesian' }, { name: 'Italian' }, { name: 'Japanese' },
    { name: 'Javanese' }, { name: 'Kannada' }, { name: 'Kazakh' },
    { name: 'Khmer' }, { name: 'Korean' }, { name: 'Kurdish' },
    { name: 'Kyrgyz' }, { name: 'Lao' }, { name: 'Latvian' },
    { name: 'Lithuanian' }, { name: 'Luxembourgish' }, { name: 'Macedonian' },
    { name: 'Malay' }, { name: 'Malayalam' }, { name: 'Maltese' },
    { name: 'Marathi' }, { name: 'Mongolian' }, { name: 'Nepali' },
    { name: 'Norwegian' }, { name: 'Odia' }, { name: 'Pashto' },
    { name: 'Polish' }, { name: 'Portuguese' }, { name: 'Punjabi' },
    { name: 'Romanian' }, { name: 'Russian' }, { name: 'Serbian' },
    { name: 'Sinhalese' }, { name: 'Slovak' }, { name: 'Slovenian' },
    { name: 'Somali' }, { name: 'Spanish' }, { name: 'Swahili' },
    { name: 'Swedish' }, { name: 'Tagalog' }, { name: 'Tajik' },
    { name: 'Tamil' }, { name: 'Telugu' }, { name: 'Thai' },
    { name: 'Tibetan' }, { name: 'Turkish' }, { name: 'Turkmen' },
    { name: 'Ukrainian' }, { name: 'Urdu' }, { name: 'Uzbek' },
    { name: 'Vietnamese' }, { name: 'Welsh' }, { name: 'Wolof' },
    { name: 'Xhosa' }, { name: 'Yoruba' }, { name: 'Zulu' },
  ]);

  // ── 7. DEGREES ────────────────────────────────────────────────────────────────
  await knex('master_degrees').insert([
    { name: 'High School Diploma / GED' },
    { name: 'Associate Degree (A.A. / A.S.)' },
    { name: "Bachelor's Degree (B.A. / B.S.)" },
    { name: "Bachelor of Engineering (B.E. / B.Tech)" },
    { name: "Bachelor of Commerce (B.Com)" },
    { name: "Bachelor of Science (B.Sc)" },
    { name: "Bachelor of Arts (B.A.)" },
    { name: "Master's Degree (M.A. / M.S.)" },
    { name: "Master of Business Administration (MBA)" },
    { name: "Master of Engineering (M.E. / M.Tech)" },
    { name: "Master of Science (M.Sc)" },
    { name: "Master of Commerce (M.Com)" },
    { name: "Doctor of Philosophy (PhD)" },
    { name: "Doctor of Medicine (MD)" },
    { name: "Juris Doctor (JD)" },
    { name: "Postgraduate Diploma / Certificate" },
    { name: "Professional Certification" },
    { name: "Diploma" },
    { name: "Vocational / Technical Qualification" },
  ]);

  // ── 8. FIELDS OF STUDY ────────────────────────────────────────────────────────
  await knex('master_fields_of_study').insert([
    { name: 'Computer Science' }, { name: 'Information Technology' },
    { name: 'Software Engineering' }, { name: 'Electrical Engineering' },
    { name: 'Mechanical Engineering' }, { name: 'Civil Engineering' },
    { name: 'Chemical Engineering' }, { name: 'Aerospace Engineering' },
    { name: 'Industrial Engineering' }, { name: 'Biomedical Engineering' },
    { name: 'Electronics & Communication' }, { name: 'Instrumentation Engineering' },
    { name: 'Data Science & Machine Learning' }, { name: 'Artificial Intelligence' },
    { name: 'Cybersecurity' }, { name: 'Networking & Telecommunications' },
    { name: 'Mathematics' }, { name: 'Statistics & Data Analysis' },
    { name: 'Physics' }, { name: 'Chemistry' }, { name: 'Biology' },
    { name: 'Biochemistry' }, { name: 'Biotechnology' }, { name: 'Environmental Science' },
    { name: 'Business Administration' }, { name: 'Finance & Accounting' },
    { name: 'Economics' }, { name: 'Marketing' }, { name: 'International Business' },
    { name: 'Human Resource Management' }, { name: 'Operations Management' },
    { name: 'Supply Chain & Logistics' }, { name: 'Project Management' },
    { name: 'Entrepreneurship' }, { name: 'Commerce' },
    { name: 'Law & Legal Studies' }, { name: 'Political Science' },
    { name: 'Public Administration' }, { name: 'International Relations' },
    { name: 'Psychology' }, { name: 'Sociology' }, { name: 'Social Work' },
    { name: 'Education & Teaching' }, { name: 'Philosophy' },
    { name: 'History' }, { name: 'English Language & Literature' },
    { name: 'Linguistics' }, { name: 'Journalism & Mass Communication' },
    { name: 'Media & Communication Studies' }, { name: 'Fine Arts' },
    { name: 'Graphic Design' }, { name: 'Architecture' }, { name: 'Interior Design' },
    { name: 'Urban Planning' }, { name: 'Medicine (MBBS / MD)' },
    { name: 'Pharmacy' }, { name: 'Dentistry' }, { name: 'Nursing' },
    { name: 'Public Health' }, { name: 'Nutrition & Dietetics' },
    { name: 'Physiotherapy' }, { name: 'Medical Laboratory Science' },
    { name: 'Agriculture' }, { name: 'Veterinary Science' },
    { name: 'Hospitality & Tourism Management' }, { name: 'Event Management' },
    { name: 'Sports Science & Management' },
  ]);

  // ── 9. CURRENCIES ─────────────────────────────────────────────────────────────
  await knex('master_currencies').insert([
    { code: 'AED', name: 'UAE Dirham',                    symbol: 'د.إ' },
    { code: 'AFN', name: 'Afghan Afghani',                symbol: '؋'   },
    { code: 'ALL', name: 'Albanian Lek',                  symbol: 'L'   },
    { code: 'AMD', name: 'Armenian Dram',                 symbol: '֏'   },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ'   },
    { code: 'AOA', name: 'Angolan Kwanza',                symbol: 'Kz'  },
    { code: 'ARS', name: 'Argentine Peso',                symbol: '$'   },
    { code: 'AUD', name: 'Australian Dollar',             symbol: 'A$'  },
    { code: 'AZN', name: 'Azerbaijani Manat',             symbol: '₼'   },
    { code: 'BAM', name: 'Bosnian Mark',                  symbol: 'KM'  },
    { code: 'BDT', name: 'Bangladeshi Taka',              symbol: '৳'   },
    { code: 'BGN', name: 'Bulgarian Lev',                 symbol: 'лв'  },
    { code: 'BHD', name: 'Bahraini Dinar',                symbol: '.د.ب'},
    { code: 'BND', name: 'Brunei Dollar',                 symbol: 'B$'  },
    { code: 'BOB', name: 'Bolivian Boliviano',            symbol: 'Bs.' },
    { code: 'BRL', name: 'Brazilian Real',                symbol: 'R$'  },
    { code: 'BWP', name: 'Botswana Pula',                 symbol: 'P'   },
    { code: 'BYN', name: 'Belarusian Ruble',              symbol: 'Br'  },
    { code: 'CAD', name: 'Canadian Dollar',               symbol: 'C$'  },
    { code: 'CDF', name: 'Congolese Franc',               symbol: 'FC'  },
    { code: 'CHF', name: 'Swiss Franc',                   symbol: 'Fr'  },
    { code: 'CLP', name: 'Chilean Peso',                  symbol: '$'   },
    { code: 'CNY', name: 'Chinese Yuan',                  symbol: '¥'   },
    { code: 'COP', name: 'Colombian Peso',                symbol: '$'   },
    { code: 'CRC', name: 'Costa Rican Colón',             symbol: '₡'   },
    { code: 'CZK', name: 'Czech Koruna',                  symbol: 'Kč'  },
    { code: 'DKK', name: 'Danish Krone',                  symbol: 'kr'  },
    { code: 'DOP', name: 'Dominican Peso',                symbol: 'RD$' },
    { code: 'DZD', name: 'Algerian Dinar',                symbol: 'دج'  },
    { code: 'EGP', name: 'Egyptian Pound',                symbol: '£'   },
    { code: 'ETB', name: 'Ethiopian Birr',                symbol: 'Br'  },
    { code: 'EUR', name: 'Euro',                          symbol: '€'   },
    { code: 'GBP', name: 'British Pound Sterling',        symbol: '£'   },
    { code: 'GEL', name: 'Georgian Lari',                 symbol: '₾'   },
    { code: 'GHS', name: 'Ghanaian Cedi',                 symbol: '₵'   },
    { code: 'GTQ', name: 'Guatemalan Quetzal',            symbol: 'Q'   },
    { code: 'HKD', name: 'Hong Kong Dollar',              symbol: 'HK$' },
    { code: 'HNL', name: 'Honduran Lempira',              symbol: 'L'   },
    { code: 'HRK', name: 'Croatian Kuna',                 symbol: 'kn'  },
    { code: 'HUF', name: 'Hungarian Forint',              symbol: 'Ft'  },
    { code: 'IDR', name: 'Indonesian Rupiah',             symbol: 'Rp'  },
    { code: 'ILS', name: 'Israeli New Shekel',            symbol: '₪'   },
    { code: 'INR', name: 'Indian Rupee',                  symbol: '₹'   },
    { code: 'IQD', name: 'Iraqi Dinar',                   symbol: 'ع.د' },
    { code: 'IRR', name: 'Iranian Rial',                  symbol: '﷼'   },
    { code: 'ISK', name: 'Icelandic Króna',               symbol: 'kr'  },
    { code: 'JMD', name: 'Jamaican Dollar',               symbol: 'J$'  },
    { code: 'JOD', name: 'Jordanian Dinar',               symbol: 'JD'  },
    { code: 'JPY', name: 'Japanese Yen',                  symbol: '¥'   },
    { code: 'KES', name: 'Kenyan Shilling',               symbol: 'KSh' },
    { code: 'KGS', name: 'Kyrgyzstani Som',               symbol: 'с'   },
    { code: 'KHR', name: 'Cambodian Riel',                symbol: '៛'   },
    { code: 'KRW', name: 'South Korean Won',              symbol: '₩'   },
    { code: 'KWD', name: 'Kuwaiti Dinar',                 symbol: 'KD'  },
    { code: 'KZT', name: 'Kazakhstani Tenge',             symbol: '₸'   },
    { code: 'LAK', name: 'Lao Kip',                       symbol: '₭'   },
    { code: 'LBP', name: 'Lebanese Pound',                symbol: '£'   },
    { code: 'LKR', name: 'Sri Lankan Rupee',              symbol: '₨'   },
    { code: 'LYD', name: 'Libyan Dinar',                  symbol: 'LD'  },
    { code: 'MAD', name: 'Moroccan Dirham',               symbol: 'MAD' },
    { code: 'MDL', name: 'Moldovan Leu',                  symbol: 'L'   },
    { code: 'MKD', name: 'Macedonian Denar',              symbol: 'ден' },
    { code: 'MMK', name: 'Myanmar Kyat',                  symbol: 'K'   },
    { code: 'MNT', name: 'Mongolian Tögrög',              symbol: '₮'   },
    { code: 'MXN', name: 'Mexican Peso',                  symbol: '$'   },
    { code: 'MYR', name: 'Malaysian Ringgit',             symbol: 'RM'  },
    { code: 'MZN', name: 'Mozambican Metical',            symbol: 'MT'  },
    { code: 'NAD', name: 'Namibian Dollar',               symbol: 'N$'  },
    { code: 'NGN', name: 'Nigerian Naira',                symbol: '₦'   },
    { code: 'NIO', name: 'Nicaraguan Córdoba',            symbol: 'C$'  },
    { code: 'NOK', name: 'Norwegian Krone',               symbol: 'kr'  },
    { code: 'NPR', name: 'Nepalese Rupee',                symbol: '₨'   },
    { code: 'NZD', name: 'New Zealand Dollar',            symbol: 'NZ$' },
    { code: 'OMR', name: 'Omani Rial',                    symbol: '﷼'   },
    { code: 'PAB', name: 'Panamanian Balboa',             symbol: 'B/.' },
    { code: 'PEN', name: 'Peruvian Sol',                  symbol: 'S/.' },
    { code: 'PHP', name: 'Philippine Peso',               symbol: '₱'   },
    { code: 'PKR', name: 'Pakistani Rupee',               symbol: '₨'   },
    { code: 'PLN', name: 'Polish Zloty',                  symbol: 'zł'  },
    { code: 'PYG', name: 'Paraguayan Guaraní',            symbol: 'Gs'  },
    { code: 'QAR', name: 'Qatari Riyal',                  symbol: '﷼'   },
    { code: 'RON', name: 'Romanian Leu',                  symbol: 'lei' },
    { code: 'RSD', name: 'Serbian Dinar',                 symbol: 'din' },
    { code: 'RUB', name: 'Russian Ruble',                 symbol: '₽'   },
    { code: 'RWF', name: 'Rwandan Franc',                 symbol: 'RF'  },
    { code: 'SAR', name: 'Saudi Riyal',                   symbol: '﷼'   },
    { code: 'SEK', name: 'Swedish Krona',                 symbol: 'kr'  },
    { code: 'SGD', name: 'Singapore Dollar',              symbol: 'S$'  },
    { code: 'SOS', name: 'Somali Shilling',               symbol: 'Sh'  },
    { code: 'SYP', name: 'Syrian Pound',                  symbol: '£'   },
    { code: 'THB', name: 'Thai Baht',                     symbol: '฿'   },
    { code: 'TJS', name: 'Tajikistani Somoni',            symbol: 'SM'  },
    { code: 'TMT', name: 'Turkmenistani Manat',           symbol: 'T'   },
    { code: 'TND', name: 'Tunisian Dinar',                symbol: 'DT'  },
    { code: 'TRY', name: 'Turkish Lira',                  symbol: '₺'   },
    { code: 'TWD', name: 'New Taiwan Dollar',             symbol: 'NT$' },
    { code: 'TZS', name: 'Tanzanian Shilling',            symbol: 'Sh'  },
    { code: 'UAH', name: 'Ukrainian Hryvnia',             symbol: '₴'   },
    { code: 'UGX', name: 'Ugandan Shilling',              symbol: 'Sh'  },
    { code: 'USD', name: 'US Dollar',                     symbol: '$'   },
    { code: 'UYU', name: 'Uruguayan Peso',                symbol: '$U'  },
    { code: 'UZS', name: 'Uzbekistani Sum',               symbol: 'лв'  },
    { code: 'VES', name: 'Venezuelan Bolívar',            symbol: 'Bs.S'},
    { code: 'VND', name: 'Vietnamese Dong',               symbol: '₫'   },
    { code: 'YER', name: 'Yemeni Rial',                   symbol: '﷼'   },
    { code: 'ZAR', name: 'South African Rand',            symbol: 'R'   },
    { code: 'ZMW', name: 'Zambian Kwacha',                symbol: 'ZK'  },
    { code: 'ZWL', name: 'Zimbabwean Dollar',             symbol: 'Z$'  },
  ]);

  // ── 10. NOTICE PERIODS ────────────────────────────────────────────────────────
  await knex('master_notice_periods').insert([
    { label: 'Immediately / Available Now', days: 0   },
    { label: '1 Week',                      days: 7   },
    { label: '2 Weeks',                     days: 14  },
    { label: '1 Month',                     days: 30  },
    { label: '45 Days',                     days: 45  },
    { label: '2 Months',                    days: 60  },
    { label: '3 Months',                    days: 90  },
    { label: '4 Months',                    days: 120 },
    { label: '6 Months',                    days: 180 },
    { label: 'More than 6 Months',          days: 181 },
  ]);
}
